/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Pacientes;
import model.bean.Utils;
import model.dao.DAOPct;

/**
 *
 * @author vinic
 */
public class filaDeVacinacao extends javax.swing.JFrame {

    /**
     * Creates new form filaDeVacinacao
     */
    public filaDeVacinacao() {
        initComponents();
        setLocationRelativeTo(null);
        readTableFilaNaoVacinados();
        configurarDataFila();
    }
    
    public void configurarDataFila(){
        Date data = new Date();     
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        try {
            txtFDataFila.setText(Utils.converter(data));
        } catch (Exception ex) {
            Logger.getLogger(filaDeVacinacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    
    public void readTableFila (){
        
        
        DefaultTableModel modelo = (DefaultTableModel) jTFila.getModel();
        modelo.setNumRows(0);
        DAOPct daopct = new DAOPct();
        
                
        for (Pacientes pct: daopct.exibirFila()){
            
            try {                    
                modelo.addRow(new Object[]{
                    pct.getId(),
                    pct.getNome(),
                    pct.getIdade(),
                    pct.isProfissao(),
                    Utils.converter(pct.getDataa()),
                    pct.getVacinacao(),
                    pct.getPrioridade(),                   
                    
                });
            } catch (Exception ex) {
                Logger.getLogger(GerarRelatorio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    public void readTableFilaNaoVacinados (){
        
        
        DefaultTableModel modelo = (DefaultTableModel) jTFila.getModel();
        modelo.setNumRows(0);
        DAOPct daopct = new DAOPct();
        
                
        for (Pacientes pct: daopct.exibirFilaNaoVacinados()){
            
            try {                    
                modelo.addRow(new Object[]{
                    pct.getId(),
                    pct.getNome(),
                    pct.getIdade(),
                    pct.isProfissao(),
                    Utils.converter(pct.getDataa()),
                    pct.getVacinacao(),
                    pct.getPrioridade(),                   
                    
                });
            } catch (Exception ex) {
                Logger.getLogger(GerarRelatorio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTFila = new javax.swing.JTable();
        VacinaCheck = new javax.swing.JCheckBox();
        confirmarButtonFila = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtFDataFila = new javax.swing.JFormattedTextField();
        logoutFilaButton = new javax.swing.JButton();
        txtIdPct = new javax.swing.JTextField();
        txtPrioPct = new javax.swing.JTextField();
        exibirVacinadosButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fila de Vacinação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jTFila.setBackground(new java.awt.Color(153, 153, 153));
        jTFila.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Idade", "Profissão", "Data", "Vacinado", "Prioridade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTFila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFilaMouseClicked(evt);
            }
        });
        jTFila.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFilaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTFila);

        VacinaCheck.setBackground(new java.awt.Color(153, 153, 153));
        VacinaCheck.setText("Vacinado");

        confirmarButtonFila.setBackground(new java.awt.Color(102, 51, 255));
        confirmarButtonFila.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        confirmarButtonFila.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\accept.png")); // NOI18N
        confirmarButtonFila.setText("Confirmar");
        confirmarButtonFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarButtonFilaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\date.png")); // NOI18N
        jLabel3.setText("Data de vacinação:");

        txtFDataFila.setEditable(false);
        try {
            txtFDataFila.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFDataFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFDataFilaActionPerformed(evt);
            }
        });

        logoutFilaButton.setBackground(new java.awt.Color(102, 51, 255));
        logoutFilaButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        logoutFilaButton.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\disconnect.png")); // NOI18N
        logoutFilaButton.setText("Logout");
        logoutFilaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutFilaButtonActionPerformed(evt);
            }
        });

        exibirVacinadosButton.setBackground(new java.awt.Color(102, 51, 255));
        exibirVacinadosButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        exibirVacinadosButton.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\table_go.png")); // NOI18N
        exibirVacinadosButton.setText("Exibir Vacinados");
        exibirVacinadosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirVacinadosButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtFDataFila, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtIdPct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(VacinaCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(confirmarButtonFila))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPrioPct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(exibirVacinadosButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutFilaButton)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtFDataFila, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VacinaCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmarButtonFila, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdPct, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrioPct, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutFilaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(exibirVacinadosButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(110, 50, 692, 480);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\vinic\\Downloads\\3722529_1.jpg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-40, -10, 1000, 680);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\vinic\\Downloads\\3722529_1.jpg")); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-40, -10, 980, 680);

        setBounds(0, 0, 927, 585);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutFilaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutFilaButtonActionPerformed
        int escolha = JOptionPane.showConfirmDialog(null, "Deseja realiza logout?", "Logout?", JOptionPane.YES_NO_OPTION);
        switch (escolha){
            default :
            JOptionPane.showMessageDialog(null, "Acao cancelada.");
            break;
            case JOptionPane.YES_OPTION:
        this.dispose();
        TelaLogin tl = new TelaLogin();
        tl.setVisible(true);
        }
    }//GEN-LAST:event_logoutFilaButtonActionPerformed

    private void txtFDataFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFDataFilaActionPerformed

    }//GEN-LAST:event_txtFDataFilaActionPerformed

    private void confirmarButtonFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButtonFilaActionPerformed
        if (jTFila.getSelectedRow() != -1){
            if (VacinaCheck.isSelected()){
                Pacientes pct = new Pacientes();
                DAOPct daopct = new DAOPct();

                pct.setId((int)jTFila.getValueAt(jTFila.getSelectedRow(), 0));

                try {              
                    pct.setDataa(Utils.converter(txtFDataFila.getText()));
                } catch (Exception ex) {
                    Logger.getLogger(filaDeVacinacao.class.getName()).log(Level.SEVERE, null, ex);
                }            
                if(VacinaCheck.isSelected()){
                    pct.vacinacao = "Sim";
                    JOptionPane.showMessageDialog(null, "Vacinado!");
                }
                else{
                    pct.vacinacao = " ";
                }

                daopct.adicionarVacina(pct);
                readTableFilaNaoVacinados();
            }
            else {
                JOptionPane.showMessageDialog(null, "Confirme a vacina!");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um Paciente para ser vacinado!");
        }
    }//GEN-LAST:event_confirmarButtonFilaActionPerformed

    private void jTFilaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFilaKeyReleased

    }//GEN-LAST:event_jTFilaKeyReleased

    private void jTFilaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFilaMouseClicked
        if (jTFila.getSelectedRow() != -1 ){
            txtIdPct.setText(jTFila.getValueAt(jTFila.getSelectedRow(), 0).toString());         
        }else {
            JOptionPane.showMessageDialog(null, "Selecione um Paciente");
        }
    }//GEN-LAST:event_jTFilaMouseClicked

    private void exibirVacinadosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirVacinadosButtonActionPerformed
        this.dispose();
        
        FilaDeVacinados fdv = new FilaDeVacinados();
        fdv.setVisible(true);
    }//GEN-LAST:event_exibirVacinadosButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(filaDeVacinacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(filaDeVacinacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(filaDeVacinacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(filaDeVacinacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new filaDeVacinacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox VacinaCheck;
    private javax.swing.JButton confirmarButtonFila;
    private javax.swing.JButton exibirVacinadosButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTFila;
    private javax.swing.JButton logoutFilaButton;
    private javax.swing.JFormattedTextField txtFDataFila;
    private javax.swing.JTextField txtIdPct;
    private javax.swing.JTextField txtPrioPct;
    // End of variables declaration//GEN-END:variables
}
