/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

//import Connection.ConnectionFactory;
//import java.sql.Connection;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Pacientes;
import model.bean.Utils;
import model.dao.DAOPct;

/**
 *
 * @author vinic
 */
public class GerarRelatorio extends javax.swing.JFrame {

    /**
     * Creates new form GerarRelatorio
     */
    public GerarRelatorio() {
        initComponents();
        setLocationRelativeTo(null);
        readTable();
        
        groupIdades.add(jRadioButton1);
        groupIdades.add(jRadioButton2);
        groupIdades.add(jRadioButton3);
        groupIdades.add(jRadioButton4);
    }
    public void readTable (){
        
        
        DefaultTableModel modelo = (DefaultTableModel) jTRel.getModel();
        modelo.setNumRows(0);
        DAOPct daopct = new DAOPct();
        
        List <Pacientes> pacientes = daopct.listar();
        Collections.sort(pacientes);
                
        for (Pacientes pct: pacientes){
            
            try {                    
                modelo.addRow(new Object[]{
                    pct.getIdade(),
                    Utils.converter(pct.getDataa())
                });
            } catch (Exception ex) {
                Logger.getLogger(GerarRelatorio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

     public void readTableForRelatorioMaior90 (String dataini, String datafin)throws Exception{
        
        
        DefaultTableModel modelo = (DefaultTableModel) jTRel.getModel();
        modelo.setNumRows(0);
        DAOPct daopct = new DAOPct();
        
        List <Pacientes> pacientes = daopct.gerarRelatorio90(dataini, datafin);
        Collections.sort(pacientes);
        
        for (Pacientes pct: pacientes){
            
            System.out.println(pct);
        
            modelo.addRow(new Object[]{
                    pct.getIdade(),
                    Utils.converter(pct.getDataa())
            });
        }

    }
     public void readTableForRelatorioMaior70 (String dataini, String datafin)throws Exception{
        
        
        DefaultTableModel modelo = (DefaultTableModel) jTRel.getModel();
        modelo.setNumRows(0);
        DAOPct daopct = new DAOPct();
        
        List <Pacientes> pacientes = daopct.gerarRelatorioMaior70(dataini, datafin);
        Collections.sort(pacientes);
        
        for (Pacientes pct: pacientes){
            
            System.out.println(pct);
        
            modelo.addRow(new Object[]{
                    pct.getIdade(),
                    Utils.converter(pct.getDataa())
            });
        }

    }
     public void readTableForRelatorioMaior50 (String dataini, String datafin)throws Exception{
        
        
        DefaultTableModel modelo = (DefaultTableModel) jTRel.getModel();
        modelo.setNumRows(0);
        DAOPct daopct = new DAOPct();
        
        List <Pacientes> pacientes = daopct.gerarRelatorioMaior50(dataini, datafin);
        Collections.sort(pacientes);
        
        for (Pacientes pct: pacientes){
            
            System.out.println(pct);
        
            modelo.addRow(new Object[]{
                    pct.getIdade(),
                    Utils.converter(pct.getDataa())
            });
        }

    }
     public void readTableForRelatorioMenor50 (String dataini, String datafin)throws Exception{
        
        
        DefaultTableModel modelo = (DefaultTableModel) jTRel.getModel();
        modelo.setNumRows(0);
        DAOPct daopct = new DAOPct();
        
        List <Pacientes> pacientes = daopct.gerarRelatorioMenor50(dataini, datafin);
        Collections.sort(pacientes);
        
        for (Pacientes pct: pacientes){
            
            System.out.println(pct);
        
            modelo.addRow(new Object[]{
                    pct.getIdade(),
                    Utils.converter(pct.getDataa())
            });
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        groupIdades = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTRel = new javax.swing.JTable();
        buscarButtonRel = new javax.swing.JButton();
        sairButtonRel = new javax.swing.JButton();
        txtFDataini = new javax.swing.JFormattedTextField();
        txtFDatafin = new javax.swing.JFormattedTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relatório", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\date_go.png")); // NOI18N
        jLabel1.setText("Data Inicial");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\date_go.png")); // NOI18N
        jLabel2.setText("Data Final");

        jTRel.setBackground(new java.awt.Color(153, 153, 153));
        jTRel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Idade", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTRel);

        buscarButtonRel.setBackground(new java.awt.Color(102, 51, 255));
        buscarButtonRel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buscarButtonRel.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\find.png")); // NOI18N
        buscarButtonRel.setText("Buscar");
        buscarButtonRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonRelActionPerformed(evt);
            }
        });

        sairButtonRel.setBackground(new java.awt.Color(102, 51, 255));
        sairButtonRel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sairButtonRel.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\arrow_undo.png")); // NOI18N
        sairButtonRel.setText("Sair");
        sairButtonRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonRelActionPerformed(evt);
            }
        });

        try {
            txtFDataini.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFDataini.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFDatainiKeyTyped(evt);
            }
        });

        try {
            txtFDatafin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFDatafin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFDatafinKeyTyped(evt);
            }
        });

        jRadioButton1.setText(">= 90");

        jRadioButton2.setText(">= 70 e < 90");

        jRadioButton3.setText(">= 50 e <70");

        jRadioButton4.setText("< 50");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\date_add.png")); // NOI18N
        jLabel4.setText("Idade");

        jButton1.setBackground(new java.awt.Color(102, 51, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\table_refresh.png")); // NOI18N
        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtFDataini, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFDatafin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jRadioButton1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadioButton2))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jRadioButton4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton3))))
                        .addGap(0, 65, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buscarButtonRel)
                        .addGap(125, 125, 125)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sairButtonRel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFDataini, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFDatafin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarButtonRel)
                    .addComponent(sairButtonRel)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(140, 20, 554, 500);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\vinic\\Downloads\\3722529_1.jpg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-110, 0, 920, 680);

        setBounds(0, 0, 803, 575);
    }// </editor-fold>//GEN-END:initComponents

    private void sairButtonRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonRelActionPerformed
        int escolha = JOptionPane.showConfirmDialog(null, "Deseja Sair?", "Sair?", JOptionPane.YES_NO_OPTION);
        switch (escolha){
            default :
            JOptionPane.showMessageDialog(null, "Acao cancelada.");
            break;
            case JOptionPane.YES_OPTION :
        this.dispose();
        
        TelaPrincipalAdm tlpa = new TelaPrincipalAdm();
        tlpa.setVisible(true);
        }
    }//GEN-LAST:event_sairButtonRelActionPerformed

    private void buscarButtonRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonRelActionPerformed
            boolean maior90 = jRadioButton1.isSelected();
            boolean maior70 = jRadioButton2.isSelected();
            boolean maior50 = jRadioButton3.isSelected();
            boolean menor50 = jRadioButton4.isSelected();
            
            if (maior90 == false && maior70 == false && maior50 == false && menor50 == false){
                JOptionPane.showMessageDialog(null, "Selecione as idades!");
            }                
            else{
                try{
                    
                if(jRadioButton1.isSelected()){
                        readTableForRelatorioMaior90(txtFDataini.getText(), txtFDatafin.getText());
                }
                else if(jRadioButton2.isSelected()){
                        readTableForRelatorioMaior70(txtFDataini.getText(), txtFDatafin.getText());
                }
                else if(jRadioButton3.isSelected()){
                        readTableForRelatorioMaior50(txtFDataini.getText(), txtFDatafin.getText());
                }
                else if(jRadioButton4.isSelected()){
                        readTableForRelatorioMenor50(txtFDataini.getText(), txtFDatafin.getText());
                }
                    
                    }
            catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Sistema indisponivel, tente novamente mais tarde");
            }
        }       
    }//GEN-LAST:event_buscarButtonRelActionPerformed

    private void txtFDatainiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFDatainiKeyTyped
        char TestChar = evt.getKeyChar();
        if(!(Character.isDigit(TestChar)))
            evt.consume();
    }//GEN-LAST:event_txtFDatainiKeyTyped

    private void txtFDatafinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFDatafinKeyTyped
        char TestChar = evt.getKeyChar();
        if(!(Character.isDigit(TestChar)))
            evt.consume();
    }//GEN-LAST:event_txtFDatafinKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        readTable();
        
        txtFDataini.setText("");
        txtFDatafin.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerarRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerarRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerarRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerarRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerarRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButtonRel;
    private javax.swing.ButtonGroup groupIdades;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTRel;
    private javax.swing.JButton sairButtonRel;
    private javax.swing.JFormattedTextField txtFDatafin;
    private javax.swing.JFormattedTextField txtFDataini;
    // End of variables declaration//GEN-END:variables
}
