package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import javax.swing.table.TableRowSorter;
import model.bean.Administradores;
import model.dao.DAOAdm;



/**
 *
 * @author vinic
 */
public class GerenciadorAdm extends javax.swing.JFrame {

    /**
     * Creates new form GerenciadorAdm
     */
 
    
    
    
    public GerenciadorAdm() {
        initComponents();
        setLocationRelativeTo(null);
               
        readTable();
   
    }
    
    public void readTable (){
        
        
        DefaultTableModel modelo = (DefaultTableModel) jTAdm.getModel();
        modelo.setNumRows(0);
        DAOAdm daoadm = new DAOAdm();
        
        for (Administradores adm: daoadm.listar()){
            
            modelo.addRow(new Object[]{
                    adm.getId(),
                    adm.getNome(),
                    adm.getIdade(),
                    adm.getEndereco(),
                    adm.getCpf(),
                    adm.getSenha()
            });
            
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdAdm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomeAdm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        adicionarAdmButton = new javax.swing.JButton();
        atualizarAdmButton = new javax.swing.JButton();
        removerAdmButton = new javax.swing.JButton();
        cancelarAdmButton = new javax.swing.JButton();
        txtSenhaAdm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIdadeAdm = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEnderecoAdm = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFCpfAdm = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAdm = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerenciador de Administradores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("ID");

        txtIdAdm.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Nome");

        txtNomeAdm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeAdmKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Senha");

        adicionarAdmButton.setBackground(new java.awt.Color(102, 51, 255));
        adicionarAdmButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        adicionarAdmButton.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\user_add.png")); // NOI18N
        adicionarAdmButton.setText("Adicionar");
        adicionarAdmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarAdmButtonActionPerformed(evt);
            }
        });

        atualizarAdmButton.setBackground(new java.awt.Color(102, 51, 255));
        atualizarAdmButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        atualizarAdmButton.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\user_edit.png")); // NOI18N
        atualizarAdmButton.setText("Atualizar");
        atualizarAdmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarAdmButtonActionPerformed(evt);
            }
        });

        removerAdmButton.setBackground(new java.awt.Color(102, 51, 255));
        removerAdmButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        removerAdmButton.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\user_delete.png")); // NOI18N
        removerAdmButton.setText("Remover");
        removerAdmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerAdmButtonActionPerformed(evt);
            }
        });

        cancelarAdmButton.setBackground(new java.awt.Color(102, 51, 255));
        cancelarAdmButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cancelarAdmButton.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\arrow_undo.png")); // NOI18N
        cancelarAdmButton.setText("Sair");
        cancelarAdmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarAdmButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Idade");

        txtIdadeAdm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdadeAdmKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Endereço");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("CPF");

        try {
            txtFCpfAdm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(txtIdAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(240, 240, 240))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtEnderecoAdm)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(101, 101, 101))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtFCpfAdm)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtIdadeAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(78, 78, 78)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSenhaAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(adicionarAdmButton)
                                .addGap(18, 18, 18)
                                .addComponent(atualizarAdmButton)
                                .addGap(40, 40, 40)
                                .addComponent(removerAdmButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelarAdmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnderecoAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFCpfAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeAdm))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdadeAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtSenhaAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarAdmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizarAdmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removerAdmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarAdmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(100, 30, 700, 355);

        jTAdm.setBackground(new java.awt.Color(153, 153, 153));
        jTAdm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Idade", "Endereço", "CPF", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTAdm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTAdmMouseClicked(evt);
            }
        });
        jTAdm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTAdmKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTAdm);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(100, 390, 700, 237);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\vinic\\Downloads\\3722529_1.jpg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-40, -10, 950, 680);

        setBounds(0, 0, 913, 689);
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarAdmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarAdmButtonActionPerformed
        String nomeAdm = txtNomeAdm.getText();
        String idadeAdm = txtIdadeAdm.getText();
        String enderecoAdm = txtEnderecoAdm.getText();
        String cpfAdm = txtFCpfAdm.getText();
        String senhaAdm = txtSenhaAdm.getText();
        
        if (nomeAdm == null || nomeAdm.length() == 0 
                || enderecoAdm.length() == 0 || enderecoAdm == null
                || idadeAdm.length() == 0 || idadeAdm == null
                || cpfAdm.length() == 0 || cpfAdm == null
                || senhaAdm.length() == 0 || senhaAdm == null){
            JOptionPane.showMessageDialog(null, "Por favor, preencha os campos corretamente");                 
        }
        else{       
            Administradores adms = new Administradores();
            DAOAdm daoadm = new DAOAdm();
            
            adms.setNome(txtNomeAdm.getText());
            adms.setSenha(txtSenhaAdm.getText());
            adms.setIdade(Integer.parseInt(txtIdadeAdm.getText()));
            adms.setEndereco(txtEnderecoAdm.getText());
            adms.setCpf(txtFCpfAdm.getText());
            
            daoadm.inserirAdministradores(adms);
        
            txtIdAdm.setText("");
            txtNomeAdm.setText("");
            txtSenhaAdm.setText("");
            txtIdadeAdm.setText("");
            txtEnderecoAdm.setText("");
            txtFCpfAdm.setText("");
            
            readTable();
        
        }  
    }//GEN-LAST:event_adicionarAdmButtonActionPerformed

    private void removerAdmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerAdmButtonActionPerformed
        if (jTAdm.getSelectedRow() != -1 ){
            
        int escolha = JOptionPane.showConfirmDialog(null, "Deseja Remover?", "Remover?", JOptionPane.YES_NO_OPTION);
        switch (escolha){
            default :
                JOptionPane.showMessageDialog(null, "O Administrador nao sera excluido.");
                break;
            case JOptionPane.YES_OPTION :
        try{
            Administradores adms = new Administradores();
            DAOAdm daoadm = new DAOAdm();
            
            adms.setId((int)jTAdm.getValueAt(jTAdm.getSelectedRow(), 0));
            
            daoadm.excluirAdm(adms);
            
            JOptionPane.showMessageDialog(null, "Administrador removido!");
            
            txtIdAdm.setText("");
            txtNomeAdm.setText("");
            txtSenhaAdm.setText("");
            txtIdadeAdm.setText("");
            txtEnderecoAdm.setText("");
            txtFCpfAdm.setText("");            
            
            readTable();
            
        } 
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Sistema indisponivel, tente novamente mais tarde.");
                }
            }
        } 
        else {
            JOptionPane.showMessageDialog(null, "Selecione um Administrador para remover");
        }
    }//GEN-LAST:event_removerAdmButtonActionPerformed

    private void atualizarAdmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarAdmButtonActionPerformed
        if (jTAdm.getSelectedRow() != -1 ){ 
            
            Administradores adms = new Administradores();
            DAOAdm daoadm = new DAOAdm();
            
            adms.setNome(txtNomeAdm.getText());
            adms.setSenha(txtSenhaAdm.getText());
            adms.setIdade(Integer.parseInt(txtIdadeAdm.getText()));
            adms.setEndereco(txtEnderecoAdm.getText());
            adms.setCpf(txtFCpfAdm.getText());
            adms.setId((int)jTAdm.getValueAt(jTAdm.getSelectedRow(), 0));
            
            daoadm.atualizarAdministradores(adms);
            
            
            txtIdAdm.setText("");
            txtNomeAdm.setText("");
            txtSenhaAdm.setText("");
            txtIdadeAdm.setText("");
            txtEnderecoAdm.setText("");
            txtFCpfAdm.setText("");  

            
            readTable();
        }else {
            JOptionPane.showMessageDialog(null, "Selecione um Administrador para atualizar");       
        }
    }//GEN-LAST:event_atualizarAdmButtonActionPerformed

    private void jTAdmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTAdmMouseClicked
        if (jTAdm.getSelectedRow() != -1 ){
            
            
            txtIdAdm.setText(jTAdm.getValueAt(jTAdm.getSelectedRow(), 0).toString());
            txtNomeAdm.setText(jTAdm.getValueAt(jTAdm.getSelectedRow(), 1).toString());
            txtIdadeAdm.setText(jTAdm.getValueAt(jTAdm.getSelectedRow(), 2).toString());
            txtEnderecoAdm.setText(jTAdm.getValueAt(jTAdm.getSelectedRow(), 3).toString());
            txtFCpfAdm.setText(jTAdm.getValueAt(jTAdm.getSelectedRow(), 4).toString());
            txtSenhaAdm.setText(jTAdm.getValueAt(jTAdm.getSelectedRow(), 5).toString());
        }else {
            JOptionPane.showMessageDialog(null, "Selecione um Administrador.");
        }
    }//GEN-LAST:event_jTAdmMouseClicked

    private void jTAdmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTAdmKeyReleased
        
    }//GEN-LAST:event_jTAdmKeyReleased

    private void cancelarAdmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarAdmButtonActionPerformed
        int escolha = JOptionPane.showConfirmDialog(null, "Deseja Sair?", "Sair?", JOptionPane.YES_NO_OPTION);
        switch (escolha){
            default :
            JOptionPane.showMessageDialog(null, "Acao cancelada.");
            break;
            case JOptionPane.YES_OPTION :
        this.dispose();
        
        TelaPrincipalAdm tpa = new TelaPrincipalAdm();
        tpa.setVisible(true);
        }
    }//GEN-LAST:event_cancelarAdmButtonActionPerformed

    private void txtIdadeAdmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdadeAdmKeyTyped
        char TestChar = evt.getKeyChar();
        if(!(Character.isDigit(TestChar)))
            evt.consume();
    }//GEN-LAST:event_txtIdadeAdmKeyTyped

    private void txtNomeAdmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeAdmKeyTyped
    }//GEN-LAST:event_txtNomeAdmKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciadorAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciadorAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciadorAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciadorAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciadorAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarAdmButton;
    private javax.swing.JButton atualizarAdmButton;
    private javax.swing.JButton cancelarAdmButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTAdm;
    private javax.swing.JButton removerAdmButton;
    private javax.swing.JTextField txtEnderecoAdm;
    private javax.swing.JFormattedTextField txtFCpfAdm;
    private javax.swing.JTextField txtIdAdm;
    private javax.swing.JTextField txtIdadeAdm;
    private javax.swing.JTextField txtNomeAdm;
    private javax.swing.JTextField txtSenhaAdm;
    // End of variables declaration//GEN-END:variables
}
