/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.bean.Administradores;
import model.bean.Atendentes;
import model.dao.DAOAdm;
import model.dao.DAOAtd;

/**
 *
 * @author vinic
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        setLocationRelativeTo(null);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        loginText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        senhaText = new javax.swing.JPasswordField();
        entrarButtonTl = new javax.swing.JButton();
        sairButtonTl = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\user.png")); // NOI18N
        jLabel2.setText("Digite seu Login");

        loginText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTextActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\lock.png")); // NOI18N
        jLabel3.setText("Digite sua senha");

        entrarButtonTl.setBackground(new java.awt.Color(102, 51, 255));
        entrarButtonTl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        entrarButtonTl.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\arrow_right.png")); // NOI18N
        entrarButtonTl.setText("Entrar");
        entrarButtonTl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        entrarButtonTl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrarButtonTlMouseEntered(evt);
            }
        });
        entrarButtonTl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarButtonTlActionPerformed(evt);
            }
        });

        sairButtonTl.setBackground(new java.awt.Color(102, 51, 255));
        sairButtonTl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sairButtonTl.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\cancel.png")); // NOI18N
        sairButtonTl.setText("Sair");
        sairButtonTl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sairButtonTlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sairButtonTlMouseExited(evt);
            }
        });
        sairButtonTl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonTlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(entrarButtonTl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(sairButtonTl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loginText)
                    .addComponent(senhaText)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(loginText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(senhaText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sairButtonTl, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(entrarButtonTl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(110, 90, 320, 250);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\vinic\\Downloads\\imagem_2021-05-30_161427.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 40, 198, 32);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\vinic\\Downloads\\3722529.jpg")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jLabel1.setMinimumSize(new java.awt.Dimension(1000, 1000));
        jLabel1.setPreferredSize(new java.awt.Dimension(1000, 1000));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-70, 0, 650, 380);

        setBounds(0, 0, 565, 407);
    }// </editor-fold>//GEN-END:initComponents

    private void loginTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginTextActionPerformed

    private void entrarButtonTlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarButtonTlActionPerformed
        
        String login = loginText.getText();
        String senha = new String (senhaText.getPassword());
        
        Administradores adm = new Administradores (login, senha);
        DAOAdm daoadm = new DAOAdm();
        
        Atendentes atd = new Atendentes(login , senha);
        DAOAtd daoatd = new DAOAtd();
        
        try {
            if (daoatd.existe(atd)){
                JOptionPane.showMessageDialog(null, "Bem vindo !");
                filaDeVacinacao tfv = new filaDeVacinacao();
                tfv.setVisible(true);
                this.dispose();
            }
            else if (daoadm.existe(adm)){
                JOptionPane.showMessageDialog(null, "Bem vindo !");
                TelaPrincipalAdm tpa = new TelaPrincipalAdm();
                tpa.setVisible(true);
                this.dispose();
            }
            else {
                JOptionPane.showMessageDialog(null, "Usuario invalido");
            }
        }
        catch (Exception ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_entrarButtonTlActionPerformed

    private void sairButtonTlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonTlActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairButtonTlActionPerformed

    private void entrarButtonTlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarButtonTlMouseEntered
        
    }//GEN-LAST:event_entrarButtonTlMouseEntered

    private void sairButtonTlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairButtonTlMouseEntered
        
    }//GEN-LAST:event_sairButtonTlMouseEntered

    private void sairButtonTlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairButtonTlMouseExited
       
    }//GEN-LAST:event_sairButtonTlMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entrarButtonTl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField loginText;
    private javax.swing.JButton sairButtonTl;
    private javax.swing.JPasswordField senhaText;
    // End of variables declaration//GEN-END:variables
}
