/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author vinic
 */
public class TelaPrincipalAdm extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalAdm
     */
    public TelaPrincipalAdm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        gerenciaAdmButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        gerenciarAtdButton = new javax.swing.JButton();
        gerenciarPctButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        gerarRelButton = new javax.swing.JButton();
        logoutAdm = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administrador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\user_suit.png")); // NOI18N
        jLabel1.setText("Gerenciar Administradores");

        gerenciaAdmButton.setBackground(new java.awt.Color(102, 51, 255));
        gerenciaAdmButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        gerenciaAdmButton.setText("Gerenciar");
        gerenciaAdmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciaAdmButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\user_gray.png")); // NOI18N
        jLabel2.setText("Gerenciar Atendentes");

        gerenciarAtdButton.setBackground(new java.awt.Color(102, 51, 255));
        gerenciarAtdButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        gerenciarAtdButton.setText("Gerenciar");
        gerenciarAtdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarAtdButtonActionPerformed(evt);
            }
        });

        gerenciarPctButton.setBackground(new java.awt.Color(102, 51, 255));
        gerenciarPctButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        gerenciarPctButton.setText("Gerenciar");
        gerenciarPctButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarPctButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\group.png")); // NOI18N
        jLabel3.setText("Gerenciar pessoas a serem vacinadas");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\table_edit.png")); // NOI18N
        jLabel4.setText("Consultar relatório");

        gerarRelButton.setBackground(new java.awt.Color(102, 51, 255));
        gerarRelButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        gerarRelButton.setText("Consultar");
        gerarRelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarRelButtonActionPerformed(evt);
            }
        });

        logoutAdm.setBackground(new java.awt.Color(102, 51, 255));
        logoutAdm.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        logoutAdm.setIcon(new javax.swing.ImageIcon("F:\\dowloads\\icons projeto\\disconnect.png")); // NOI18N
        logoutAdm.setText("Logout");
        logoutAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutAdmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutAdm)
                .addGap(275, 275, 275))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(gerenciarPctButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gerenciaAdmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(gerarRelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gerenciarAtdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gerenciaAdmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gerenciarAtdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gerarRelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gerenciarPctButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(logoutAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(120, 30, 654, 420);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\vinic\\Downloads\\3722529_1.jpg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-40, -10, 950, 680);

        setBounds(0, 0, 899, 512);
    }// </editor-fold>//GEN-END:initComponents

    private void gerenciaAdmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciaAdmButtonActionPerformed
        this.dispose();
        
        GerenciadorAdm gadm = new GerenciadorAdm();
        gadm.setVisible(true);
    }//GEN-LAST:event_gerenciaAdmButtonActionPerformed

    private void gerenciarAtdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarAtdButtonActionPerformed
        this.dispose();
        
        GerenciadorAtd gatd = new GerenciadorAtd();
        gatd.setVisible(true);
    }//GEN-LAST:event_gerenciarAtdButtonActionPerformed

    private void gerarRelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarRelButtonActionPerformed
        this.dispose();
        
        GerarRelatorio grel = new GerarRelatorio();
        grel.setVisible(true);               
    }//GEN-LAST:event_gerarRelButtonActionPerformed

    private void gerenciarPctButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarPctButtonActionPerformed
        this.dispose();
        
        GerenciadorPct gpct = new GerenciadorPct();
        gpct.setVisible(true);
    }//GEN-LAST:event_gerenciarPctButtonActionPerformed

    private void logoutAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutAdmActionPerformed
        int escolha = JOptionPane.showConfirmDialog(null, "Deseja realiza logout?", "Logout?", JOptionPane.YES_NO_OPTION);
        switch (escolha){
            default :
            JOptionPane.showMessageDialog(null, "Acao cancelada.");
            break;
            case JOptionPane.YES_OPTION :
        this.dispose();
        TelaLogin tl = new TelaLogin();
        tl.setVisible(true);
        }
    }//GEN-LAST:event_logoutAdmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gerarRelButton;
    private javax.swing.JButton gerenciaAdmButton;
    private javax.swing.JButton gerenciarAtdButton;
    private javax.swing.JButton gerenciarPctButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutAdm;
    // End of variables declaration//GEN-END:variables
}
